spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sandbox_db
    username: root
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none

server:
  port: 8765